#pragma once

#define FEATURE_ROOT_SUBDIVISION 4
#define REDUNDANCY_DISTANCE 7

#define BLUR_NB_BOXES 3

#define MEAN_SHIFT_BLUR_SIGMA 8
#define MEAN_SHIFT_SPATIAL_FILTER 64
#define MEAN_SHIFT_RANGE_FILTER 20
#define MEAN_SHIFT_FIRST_OPTIM_DIST 0.5
#define MEAN_SHIFT_SECOND_OPTIM_DIST 0.1
#define MEAN_SHIFT_SPATIAL_MERGE_RATIO 0.5
#define MEAN_SHIFT_RANGE_MERGE_RATIO 0.5

#define SALIENCY_FILTER_UNIQUENESS_SIGMA 300.
#define SALIENCY_FILTER_DISTRIBUTION_SIGMA 2.
#define SALIENCY_DISTRIBUTION_INFLUENCE 6.

#define HISTOGRAM_CORRECTION_BLENDING 0.5